services:
  db:
    image: postgres:15-alpine
    container_name: treksphere_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - treksphere_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: treksphere_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - treksphere_net

  redis:
    image: redis:alpine
    container_name: treksphere_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - treksphere_net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: treksphere_redisinsight
    restart: always
    ports:
      - "8001:5540"
    depends_on:
      - redis
    networks:
      - treksphere_net

volumes:
  postgres_data:

networks:
  treksphere_net:
