package com.sep.treksphere.enums.tracking;

public enum TrackingEventType {
    EQUIPMENT_CHECKED,
    ATTENDANCE_START_RECORDED,
    SESSION_STARTED,
    CHECKPOINT_REACHED,
    CHECKPOINT_SKIPPED,
    SOS_CREATED,
    ATTENDANCE_END_RECORDED,
    SESSION_ENDED,
    SOS_RESOLVED
}
