package com.sep.treksphere.notification;

public enum NotificationEventType {
    BOOKING_CONFIRMED, BOOKING_CANCELLED, PAYMENT_SUCCESS, NEW_MESSAGE,
    TOUR_APPROVED, TOUR_PENDING_APPROVAL, TOUR_HIDDEN_VIOLATION, GROUP_JOIN_REQUEST,
    SCHEDULE_UPDATED, TOUR_REJECTED, REFUND_PENDING, REFUND_MANUAL_REVIEW,
    REFUND_OVERDUE, REFUND_COMPLETED,
    GROUP_MEMBER_APPROVED, GROUP_MEMBER_REJECTED, GROUP_MEMBER_LEFT, GROUP_DISBANDED,
    BLOG_COMMENT_ADDED
}
