package com.sep.treksphere.notification;

public enum NotificationEventType {
    BOOKING_CONFIRMED, BOOKING_CANCELLED, PAYMENT_SUCCESS, NEW_MESSAGE,
    TOUR_APPROVED, TOUR_PENDING_APPROVAL, TOUR_HIDDEN_VIOLATION, GROUP_JOIN_REQUEST,
    SCHEDULE_UPDATED, TOUR_REJECTED, REFUND_PENDING, REFUND_MANUAL_REVIEW,
    REFUND_OVERDUE, REFUND_COMPLETED,
    GROUP_MEMBER_APPROVED, GROUP_MEMBER_REJECTED, GROUP_MEMBER_LEFT, GROUP_MEMBER_REMOVED, GROUP_DISBANDED,
    GROUP_TRIP_STARTED, GROUP_TRIP_ENDED,
    GROUP_MOMENT_CREATED, GROUP_POST_ANNOUNCEMENT, GROUP_POST_COMMENT_ADDED,
    GROUP_EXPENSE_CREATED, GROUP_SETTLEMENT_PROOF_SUBMITTED, GROUP_SETTLEMENT_CONFIRMED,
    BLOG_COMMENT_ADDED, TOUR_UNHIDDEN,
    VENDOR_APPLICATION_SUBMITTED, VENDOR_APPLICATION_APPROVED, VENDOR_APPLICATION_REJECTED,
    VENDOR_STATUS_CHANGED, BLOG_HIDDEN, BLOG_DELETED, CONVERSATION_MEMBER_ADDED,
    REPORT_SUBMITTED, REPORT_RESOLVED, USER_STATUS_CHANGED
}
