package com.sep.treksphere.exception;

import com.sep.treksphere.constant.MessageConstant;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

    UNCATEGORIZED_EXCEPTION(9999, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.SYSTEM_ERROR_UNKNOWN),
    INVALID_KEY(9998, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_MESSAGE_KEY),
    VALIDATION_ERROR(9001, HttpStatus.BAD_REQUEST, MessageConstant.VALIDATION_ERROR_MSG),

    UNAUTHORIZED(1001, HttpStatus.UNAUTHORIZED, MessageConstant.UNAUTHORIZED_ACTION),
    ACCESS_DENIED(1002, HttpStatus.FORBIDDEN, MessageConstant.ACCESS_DENIED),
    USER_NOT_FOUND(1003, HttpStatus.NOT_FOUND, MessageConstant.USER_NOT_FOUND),
    EMAIL_EXISTED(1004, HttpStatus.BAD_REQUEST, MessageConstant.EMAIL_EXISTED),
    WRONG_PASSWORD(1005, HttpStatus.BAD_REQUEST, MessageConstant.WRONG_PASSWORD),
    USER_NOT_ACTIVE(1006, HttpStatus.FORBIDDEN, MessageConstant.USER_NOT_ACTIVE_OR_LOCKED),
    EMAIL_NOT_VERIFIED(1007, HttpStatus.FORBIDDEN, MessageConstant.EMAIL_NOT_VERIFIED),
    INVALID_TOKEN(1008, HttpStatus.UNAUTHORIZED, MessageConstant.INVALID_TOKEN),
    ROLE_NOT_FOUND(1009, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.ROLE_NOT_FOUND),
    ACCOUNT_LOCKED(1010, HttpStatus.FORBIDDEN, MessageConstant.ACCOUNT_LOCKED),
    ACCOUNT_DEACTIVATED(1011, HttpStatus.FORBIDDEN, MessageConstant.ACCOUNT_DEACTIVATED),
    VERIFICATION_TOKEN_EXPIRED(1012, HttpStatus.BAD_REQUEST, MessageConstant.VERIFICATION_TOKEN_EXPIRED),
    VERIFICATION_RESEND_RATE_LIMITED(1013, HttpStatus.TOO_MANY_REQUESTS, MessageConstant.VERIFICATION_RESEND_RATE_LIMITED),
    FORGOT_PASSWORD_RATE_LIMITED(1014, HttpStatus.TOO_MANY_REQUESTS, MessageConstant.FORGOT_PASSWORD_RATE_LIMITED),

    // Upload
    UPLOAD_FAILED(2001, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.UPLOAD_FAILED),
    FILE_TOO_LARGE(2002, HttpStatus.BAD_REQUEST, MessageConstant.FILE_TOO_LARGE),
    INVALID_FILE_FORMAT(2003, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_FILE_FORMAT),
    
    // Email
    EMAIL_SEND_FAILED(3001, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.EMAIL_SEND_FAILED),

    // Tour
    TOUR_NOT_FOUND(4001, HttpStatus.NOT_FOUND, MessageConstant.TOUR_NOT_FOUND),
    TOUR_NOT_BELONG_TO_VENDOR(4002, HttpStatus.FORBIDDEN, MessageConstant.TOUR_NOT_BELONG_TO_VENDOR),
    TOUR_STATUS_NOT_EDITABLE(4003, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_STATUS_NOT_EDITABLE),
    TOUR_NOT_IN_DRAFT_OR_REJECTED(4004, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_IN_DRAFT_OR_REJECTED),
    TOUR_NOT_APPROVED(4005, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_APPROVED),
    TOUR_HAS_ACTIVE_BOOKINGS(4006, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_HAS_ACTIVE_BOOKINGS),
    TOUR_NOT_IN_REJECTED_STATUS(4007, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_IN_REJECTED_STATUS),
    TOUR_UPDATE_NOT_ALLOWED(4008, HttpStatus.FORBIDDEN, MessageConstant.TOUR_UPDATE_NOT_ALLOWED),
    TOUR_NOT_DELETED(4009, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_DELETED),
    TOUR_NOT_PENDING_APPROVAL(4010, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_PENDING_APPROVAL),
    TOUR_NOT_HIDDEN(4011, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_HIDDEN),

    // Checkpoint
    CHECKPOINT_NOT_FOUND(4101, HttpStatus.NOT_FOUND, MessageConstant.CHECKPOINT_NOT_FOUND),
    CHECKPOINT_DUPLICATE_ORDER(4102, HttpStatus.BAD_REQUEST, MessageConstant.CHECKPOINT_DUPLICATE_ORDER),
    CHECKPOINT_DUPLICATE_NAME(4103, HttpStatus.BAD_REQUEST, MessageConstant.CHECKPOINT_DUPLICATE_NAME),
    CHECKPOINT_DUPLICATE_COORDINATES(4104, HttpStatus.BAD_REQUEST, MessageConstant.CHECKPOINT_DUPLICATE_COORDINATES),

    // Schedule
    SCHEDULE_NOT_FOUND(4201, HttpStatus.NOT_FOUND, MessageConstant.SCHEDULE_NOT_FOUND),
    SCHEDULE_HAS_BOOKINGS(4202, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_HAS_BOOKINGS),
    SCHEDULE_RETURN_BEFORE_DEPARTURE(4203, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_RETURN_BEFORE_DEPARTURE),
    SCHEDULE_DEPARTURE_IN_PAST(4204, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_DEPARTURE_IN_PAST),
    SCHEDULE_NOT_EDITABLE(4205, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_NOT_EDITABLE),
    TOUR_NOT_APPROVED_FOR_SCHEDULE(4206, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_APPROVED_FOR_SCHEDULE),
    SCHEDULE_CHANGE_REASON_REQUIRED(4207, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_CHANGE_REASON_REQUIRED),
    SCHEDULE_SLOTS_LESS_THAN_BOOKED(4208, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_SLOTS_LESS_THAN_BOOKED),
    SCHEDULE_SLOTS_EXCEED_MAX_CAPACITY(4209, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_SLOTS_EXCEED_MAX_CAPACITY),

    // Blog
    BLOG_NOT_FOUND(5001, HttpStatus.NOT_FOUND, MessageConstant.BLOG_NOT_FOUND),
    BLOG_COMMENT_NOT_FOUND(5002, HttpStatus.NOT_FOUND, MessageConstant.COMMENT_NOT_FOUND),
    BLOG_CANNOT_EDIT(5003, HttpStatus.FORBIDDEN, MessageConstant.BLOG_CANNOT_EDIT),
    COMMENT_CANNOT_EDIT(5004, HttpStatus.FORBIDDEN, MessageConstant.COMMENT_CANNOT_EDIT),
    COMMENT_CANNOT_DELETE(5005, HttpStatus.FORBIDDEN, MessageConstant.COMMENT_CANNOT_DELETE),
    
    // Vendor
    VENDOR_NOT_FOUND(6001, HttpStatus.NOT_FOUND, MessageConstant.VENDOR_NOT_FOUND),
    EQUIPMENT_NOT_FOUND(6002, HttpStatus.NOT_FOUND, MessageConstant.EQUIPMENT_NOT_FOUND),
    TAX_CODE_ALREADY_EXISTS(6003, HttpStatus.BAD_REQUEST, MessageConstant.TAX_CODE_ALREADY_EXISTS),
    APPLICATION_PENDING_EXISTS(6004, HttpStatus.BAD_REQUEST, MessageConstant.APPLICATION_PENDING_EXISTS),
    VENDOR_APPLICATION_NOT_FOUND(6005, HttpStatus.NOT_FOUND, MessageConstant.VENDOR_APPLICATION_NOT_FOUND),
    CONTACT_EMAIL_ALREADY_EXISTS(6006, HttpStatus.BAD_REQUEST, MessageConstant.CONTACT_EMAIL_ALREADY_EXISTS),
    CONTACT_PHONE_ALREADY_EXISTS(6007, HttpStatus.BAD_REQUEST, MessageConstant.CONTACT_PHONE_ALREADY_EXISTS),
    UNAUTHORIZED_APPLICATION_ACCESS(6008, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_APPLICATION_ACCESS),
    APPLICATION_ALREADY_PROCESSED(6009, HttpStatus.BAD_REQUEST, MessageConstant.APPLICATION_ALREADY_PROCESSED),
    CANNOT_UPDATE_APPLICATION(6100, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_UPDATE_APPLICATION),
    CANNOT_SUBMIT_APPLICATION(6101, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_SUBMIT_APPLICATION),
    CANNOT_RESUBMIT_APPLICATION(6102, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_RESUBMIT_APPLICATION),
    INVALID_REVIEW_STATUS(6103, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_REVIEW_STATUS),
    REJECTION_REASON_REQUIRED(6104, HttpStatus.BAD_REQUEST, MessageConstant.REJECTION_REASON_REQUIRED),
    INVALID_APPLICATION_FILTER_STATUS(6105, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_APPLICATION_FILTER_STATUS),
    APPLICANT_ALREADY_HAS_APPLICATION(6106, HttpStatus.CONFLICT, MessageConstant.APPLICANT_ALREADY_HAS_APPLICATION),
    APPLICANT_ALREADY_HAS_VENDOR(6107, HttpStatus.CONFLICT, MessageConstant.APPLICANT_ALREADY_HAS_VENDOR),
    UNAUTHORIZED_VENDOR_ACCESS(6010, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_VENDOR_ACCESS),
    VENDOR_REVOKED_STATUS(6011, HttpStatus.BAD_REQUEST, MessageConstant.VENDOR_REVOKED_STATUS),
    STAFF_ALREADY_EXISTS(6201, HttpStatus.BAD_REQUEST, MessageConstant.STAFF_ALREADY_EXISTS),
    STAFF_BELONGS_TO_OTHER_VENDOR(6202, HttpStatus.BAD_REQUEST, MessageConstant.STAFF_BELONGS_TO_OTHER_VENDOR),
    VENDOR_STAFF_NOT_FOUND(6203, HttpStatus.NOT_FOUND, MessageConstant.VENDOR_STAFF_NOT_FOUND),
    UNAUTHORIZED_STAFF_ACCESS(6204, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_STAFF_ACCESS),
    INVALID_DATE_RANGE(6401, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_DATE_RANGE),
    SESSION_NOT_FOUND(6501, HttpStatus.NOT_FOUND, MessageConstant.SESSION_NOT_FOUND),
    SESSION_ALREADY_STARTED(6502, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_ALREADY_STARTED),
    SESSION_ALREADY_COMPLETED(6503, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_ALREADY_COMPLETED),
    SESSION_ALREADY_CANCELLED(6504, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_ALREADY_CANCELLED),
    NOT_LEAD_COORDINATOR(6505, HttpStatus.FORBIDDEN, MessageConstant.NOT_LEAD_COORDINATOR),
    UNAUTHORIZED_SESSION_ACCESS(6506, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_SESSION_ACCESS),
    CHECKIN_OUT_OF_RANGE(6507, HttpStatus.BAD_REQUEST, MessageConstant.CHECKIN_OUT_OF_RANGE),
    INVALID_GPS_COORDINATES(6508, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_GPS_COORDINATES),
    GPS_COORDINATES_REQUIRED(6509, HttpStatus.BAD_REQUEST, MessageConstant.GPS_COORDINATES_REQUIRED),
    LATITUDE_OUT_OF_BOUNDS(6510, HttpStatus.BAD_REQUEST, MessageConstant.LATITUDE_OUT_OF_BOUNDS),
    LONGITUDE_OUT_OF_BOUNDS(6511, HttpStatus.BAD_REQUEST, MessageConstant.LONGITUDE_OUT_OF_BOUNDS),
    NO_PENDING_CHECKPOINTS(6512, HttpStatus.BAD_REQUEST, MessageConstant.NO_PENDING_CHECKPOINTS),
    SESSION_NOT_IN_PROGRESS(6513, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_NOT_IN_PROGRESS),
    INVALID_ATTENDANCE_TYPE(6514, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_ATTENDANCE_TYPE),
    PARTICIPANT_NOT_FOUND_IN_SESSION(6515, HttpStatus.BAD_REQUEST, MessageConstant.PARTICIPANT_NOT_FOUND_IN_SESSION),
    DUPLICATE_PARTICIPANT_IN_ATTENDANCE(6516, HttpStatus.BAD_REQUEST, MessageConstant.DUPLICATE_PARTICIPANT_IN_ATTENDANCE),
    UNAUTHORIZED_EQUIPMENT_CHECK(6517, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_EQUIPMENT_CHECK),
    UNAUTHORIZED_SOS_ALERT(6518, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_SOS_ALERT),
    SESSION_FOR_SOS_NOT_ACTIVE(6519, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_FOR_SOS_NOT_ACTIVE),
    SOS_ALERT_NOT_FOUND(6520, HttpStatus.NOT_FOUND, MessageConstant.SOS_ALERT_NOT_FOUND),
    SOS_ALERT_ALREADY_RESOLVED(6521, HttpStatus.BAD_REQUEST, MessageConstant.SOS_ALERT_ALREADY_RESOLVED),
    UNAUTHORIZED_RESOLVE_SOS(6522, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_RESOLVE_SOS),
    ATTENDANCE_START_REQUIRED(6523, HttpStatus.BAD_REQUEST, MessageConstant.ATTENDANCE_START_REQUIRED),
    TOUR_CHECKPOINTS_NOT_CONFIGURED(6524, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_CHECKPOINTS_NOT_CONFIGURED),
    TOUR_CHECKPOINT_COORDINATES_REQUIRED(6525, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_CHECKPOINT_COORDINATES_REQUIRED),
    SESSION_START_DATE_INVALID(6526, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_START_DATE_INVALID),
    SCHEDULE_NOT_AVAILABLE_FOR_START(6527, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_NOT_AVAILABLE_FOR_START),
    START_ATTENDANCE_INCOMPLETE(6528, HttpStatus.BAD_REQUEST, MessageConstant.START_ATTENDANCE_INCOMPLETE),
    NO_PRESENT_PARTICIPANTS(6529, HttpStatus.BAD_REQUEST, MessageConstant.NO_PRESENT_PARTICIPANTS),
    SESSION_EQUIPMENT_NOT_READY(6530, HttpStatus.BAD_REQUEST, MessageConstant.SESSION_EQUIPMENT_NOT_READY),
    SESSION_CHECKPOINT_LOGS_ALREADY_INITIALIZED(6531, HttpStatus.CONFLICT, MessageConstant.SESSION_CHECKPOINT_LOGS_ALREADY_INITIALIZED),
    // Porter
    PORTER_NOT_FOUND(6301, HttpStatus.NOT_FOUND, MessageConstant.PORTER_NOT_FOUND),
    // Booking & Voucher Error Codes
    BOOKING_NOT_FOUND(7001, HttpStatus.NOT_FOUND, MessageConstant.BOOKING_NOT_FOUND),
    NOT_ENOUGH_SLOTS(7002, HttpStatus.BAD_REQUEST, MessageConstant.NOT_ENOUGH_SLOTS),
    VOUCHER_NOT_FOUND(7003, HttpStatus.NOT_FOUND, MessageConstant.VOUCHER_NOT_FOUND),
    VOUCHER_EXPIRED(7004, HttpStatus.BAD_REQUEST, MessageConstant.VOUCHER_EXPIRED),
    VOUCHER_MAX_USAGE_REACHED(7005, HttpStatus.BAD_REQUEST, MessageConstant.VOUCHER_MAX_USAGE_REACHED),
    VOUCHER_MIN_ORDER_VALUE_NOT_MET(7006, HttpStatus.BAD_REQUEST, MessageConstant.VOUCHER_MIN_ORDER_VALUE_NOT_MET),
    VOUCHER_VENDOR_MISMATCH(7007, HttpStatus.BAD_REQUEST, MessageConstant.VOUCHER_VENDOR_MISMATCH),
    BOOKING_CANNOT_CANCEL(7008, HttpStatus.BAD_REQUEST, MessageConstant.BOOKING_CANNOT_CANCEL),
    INVALID_BOOKING_STATUS(7009, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_BOOKING_STATUS),
    BOOKING_NOT_CANCELLED(7010, HttpStatus.BAD_REQUEST, MessageConstant.BOOKING_NOT_CANCELLED),
    VOUCHER_CODE_ALREADY_EXISTS(7011, HttpStatus.BAD_REQUEST, MessageConstant.VOUCHER_CODE_ALREADY_EXISTS),
    VOUCHER_VALID_DATE_ERROR(7012, HttpStatus.BAD_REQUEST, MessageConstant.VOUCHER_VALID_DATE_ERROR),
    INVALID_DISCOUNT_VALUE(7013, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_DISCOUNT_VALUE),
    // Logistics
    TOUR_SESSION_NOT_FOUND(8001, HttpStatus.NOT_FOUND, MessageConstant.TOUR_SESSION_NOT_FOUND),
    TOUR_SESSION_ALREADY_STARTED(8002, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_SESSION_ALREADY_STARTED),
    COORDINATOR_NOT_FOUND(8003, HttpStatus.NOT_FOUND, MessageConstant.COORDINATOR_NOT_FOUND),
    COORDINATOR_SCHEDULE_CONFLICT(8004, HttpStatus.BAD_REQUEST, MessageConstant.COORDINATOR_SCHEDULE_CONFLICT),
    COORDINATOR_IN_PROGRESS_TOUR(8005, HttpStatus.BAD_REQUEST, MessageConstant.COORDINATOR_IN_PROGRESS_TOUR),
    COORDINATOR_ALREADY_ASSIGNED(8006, HttpStatus.BAD_REQUEST, MessageConstant.COORDINATOR_ALREADY_ASSIGNED),
    SCHEDULE_NOT_BELONG_TO_VENDOR(8007, HttpStatus.FORBIDDEN, MessageConstant.SCHEDULE_NOT_BELONG_TO_VENDOR),
    CANCEL_TOO_CLOSE_TO_DEPARTURE(8008, HttpStatus.BAD_REQUEST, MessageConstant.CANCEL_TOO_CLOSE_TO_DEPARTURE),
    PORTER_ALREADY_ASSIGNED(8009, HttpStatus.BAD_REQUEST, MessageConstant.PORTER_ALREADY_ASSIGNED),
    PORTER_SCHEDULE_CONFLICT(8010, HttpStatus.BAD_REQUEST, MessageConstant.PORTER_SCHEDULE_CONFLICT),
    PORTER_SCHEDULE_NOT_FOUND(8011, HttpStatus.NOT_FOUND, MessageConstant.PORTER_SCHEDULE_NOT_FOUND),
    EQUIPMENT_ALREADY_ASSIGNED(8012, HttpStatus.BAD_REQUEST, MessageConstant.EQUIPMENT_ALREADY_ASSIGNED),
    NOT_ENOUGH_EQUIPMENT_IN_STOCK(8013, HttpStatus.BAD_REQUEST, MessageConstant.NOT_ENOUGH_EQUIPMENT_IN_STOCK),
    SESSION_EQUIPMENT_NOT_FOUND(8014, HttpStatus.NOT_FOUND, MessageConstant.SESSION_EQUIPMENT_NOT_FOUND),
    SESSION_EQUIPMENT_NOT_BELONG_TO_VENDOR(8016, HttpStatus.FORBIDDEN, MessageConstant.SESSION_EQUIPMENT_NOT_BELONG_TO_VENDOR),
    INVALID_RETURN_QUANTITY(8015, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_RETURN_QUANTITY),

    // Matching Group
    MATCHING_GROUP_NOT_FOUND(8101, HttpStatus.NOT_FOUND, MessageConstant.MATCHING_GROUP_NOT_FOUND),
    INVALID_TARGET_DATE(8102, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_TARGET_DATE),
    INVALID_DEADLINE(8103, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_DEADLINE),
    ALREADY_HAS_ACTIVE_GROUP(8104, HttpStatus.BAD_REQUEST, MessageConstant.ALREADY_HAS_ACTIVE_GROUP),
    MATCHING_GROUP_NOT_OPEN(8105, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_GROUP_NOT_OPEN),
    MATCHING_DEADLINE_PASSED(8106, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_DEADLINE_PASSED),
    MATCHING_GROUP_FULL(8107, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_GROUP_FULL),
    ALREADY_MEMBER(8108, HttpStatus.BAD_REQUEST, MessageConstant.ALREADY_MEMBER),
    JOIN_REQUEST_PENDING(8109, HttpStatus.BAD_REQUEST, MessageConstant.JOIN_REQUEST_PENDING),
    MATCHING_MEMBER_NOT_FOUND(8110, HttpStatus.NOT_FOUND, MessageConstant.MATCHING_MEMBER_NOT_FOUND),
    UNAUTHORIZED_APPROVE_MEMBER(8111, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_APPROVE_MEMBER),
    MEMBER_ALREADY_APPROVED(8112, HttpStatus.BAD_REQUEST, MessageConstant.MEMBER_ALREADY_APPROVED),
    INVALID_MEMBER_STATUS(8113, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_MEMBER_STATUS),
    UNAUTHORIZED_REJECT_MEMBER(8114, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_REJECT_MEMBER),
    MEMBER_ALREADY_REJECTED(8115, HttpStatus.BAD_REQUEST, MessageConstant.MEMBER_ALREADY_REJECTED),
    OWNER_CANNOT_LEAVE(8116, HttpStatus.BAD_REQUEST, MessageConstant.OWNER_CANNOT_LEAVE),
    NOT_A_MEMBER(8117, HttpStatus.BAD_REQUEST, MessageConstant.NOT_A_MEMBER),
    UNAUTHORIZED_DISBAND_GROUP(8118, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_DISBAND_GROUP),
    UNAUTHORIZED_VIEW_JOIN_REQUESTS(8119, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_VIEW_JOIN_REQUESTS),
    MATCHING_TOUR_NOT_APPROVED(8120, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_TOUR_NOT_APPROVED),
    MATCHING_TOUR_NOT_AVAILABLE(8121, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_TOUR_NOT_AVAILABLE),
    MATCHING_GROUP_SIZE_EXCEEDS_TOUR_CAPACITY(8122, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_GROUP_SIZE_EXCEEDS_TOUR_CAPACITY),
    MATCHING_OWNER_CANNOT_JOIN(8123, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_OWNER_CANNOT_JOIN),
    MATCHING_TARGET_DATE_PASSED(8124, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_TARGET_DATE_PASSED),
    INVALID_JOIN_REQUEST_FILTER_STATUS(8125, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_JOIN_REQUEST_FILTER_STATUS),
    INVALID_JOIN_REQUEST_PAGINATION(8126, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_JOIN_REQUEST_PAGINATION),
    NO_PENDING_JOIN_REQUEST(8127, HttpStatus.BAD_REQUEST, MessageConstant.NO_PENDING_JOIN_REQUEST),
    NOT_ACCEPTED_MATCHING_MEMBER(8128, HttpStatus.BAD_REQUEST, MessageConstant.NOT_ACCEPTED_MATCHING_MEMBER),
    MATCHING_GROUP_CANNOT_BE_DISBANDED(8129, HttpStatus.BAD_REQUEST, MessageConstant.MATCHING_GROUP_CANNOT_BE_DISBANDED),

    // Review
    REVIEW_NOT_FOUND(9101, HttpStatus.NOT_FOUND, MessageConstant.REVIEW_NOT_FOUND),
    REVIEW_ALREADY_EXISTS(9102, HttpStatus.BAD_REQUEST, MessageConstant.REVIEW_ALREADY_EXISTS),
    REVIEW_BOOKING_NOT_COMPLETED(9103, HttpStatus.BAD_REQUEST, MessageConstant.REVIEW_BOOKING_NOT_COMPLETED),
    REVIEW_BOOKING_NOT_OWNED(9104, HttpStatus.FORBIDDEN, MessageConstant.REVIEW_BOOKING_NOT_OWNED),
    REVIEW_INVALID_STATUS(9105, HttpStatus.BAD_REQUEST, MessageConstant.REVIEW_INVALID_STATUS_MSG),

    // Chat
    CONVERSATION_NOT_FOUND(9110, HttpStatus.NOT_FOUND, MessageConstant.CONVERSATION_NOT_FOUND),
    CONVERSATION_ALREADY_EXISTS(9111, HttpStatus.BAD_REQUEST, MessageConstant.CONVERSATION_ALREADY_EXISTS),
    RECIPIENT_NOT_FOUND(9113, HttpStatus.NOT_FOUND, MessageConstant.RECIPIENT_NOT_FOUND),
    CANNOT_CHAT_WITH_SELF(9114, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_CHAT_WITH_SELF);


    private final int code;
    private final HttpStatus httpStatus;
    private final String message;

    ErrorCode(int code, HttpStatus httpStatus, String message) {
        this.code = code;
        this.httpStatus = httpStatus;
        this.message = message;
    }
}
