package com.sep.treksphere.exception;

import com.sep.treksphere.constant.MessageConstant;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

    UNCATEGORIZED_EXCEPTION(9999, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.SYSTEM_ERROR_UNKNOWN),
    INVALID_KEY(9998, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_MESSAGE_KEY),
    VALIDATION_ERROR(9001, HttpStatus.BAD_REQUEST, MessageConstant.VALIDATION_ERROR_MSG),

    UNAUTHORIZED(1001, HttpStatus.UNAUTHORIZED, MessageConstant.UNAUTHORIZED_ACTION),
    ACCESS_DENIED(1002, HttpStatus.FORBIDDEN, MessageConstant.ACCESS_DENIED),
    USER_NOT_FOUND(1003, HttpStatus.NOT_FOUND, MessageConstant.USER_NOT_FOUND),
    EMAIL_EXISTED(1004, HttpStatus.BAD_REQUEST, MessageConstant.EMAIL_EXISTED),
    WRONG_PASSWORD(1005, HttpStatus.BAD_REQUEST, MessageConstant.WRONG_PASSWORD),
    USER_NOT_ACTIVE(1006, HttpStatus.FORBIDDEN, MessageConstant.USER_NOT_ACTIVE_OR_LOCKED),
    EMAIL_NOT_VERIFIED(1007, HttpStatus.FORBIDDEN, MessageConstant.EMAIL_NOT_VERIFIED),
    INVALID_TOKEN(1008, HttpStatus.UNAUTHORIZED, MessageConstant.INVALID_TOKEN),
    ROLE_NOT_FOUND(1009, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.ROLE_NOT_FOUND),

    // Upload
    UPLOAD_FAILED(2001, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.UPLOAD_FAILED),
    FILE_TOO_LARGE(2002, HttpStatus.BAD_REQUEST, MessageConstant.FILE_TOO_LARGE),
    INVALID_FILE_FORMAT(2003, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_FILE_FORMAT),
    
    // Email
    EMAIL_SEND_FAILED(3001, HttpStatus.INTERNAL_SERVER_ERROR, MessageConstant.EMAIL_SEND_FAILED),

    // Tour
    TOUR_NOT_FOUND(4001, HttpStatus.NOT_FOUND, MessageConstant.TOUR_NOT_FOUND),
    TOUR_NOT_BELONG_TO_VENDOR(4002, HttpStatus.FORBIDDEN, MessageConstant.TOUR_NOT_BELONG_TO_VENDOR),
    TOUR_STATUS_NOT_EDITABLE(4003, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_STATUS_NOT_EDITABLE),
    TOUR_NOT_IN_DRAFT_OR_REJECTED(4004, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_IN_DRAFT_OR_REJECTED),
    TOUR_NOT_APPROVED(4005, HttpStatus.BAD_REQUEST, MessageConstant.TOUR_NOT_APPROVED),

    // Checkpoint
    CHECKPOINT_NOT_FOUND(4101, HttpStatus.NOT_FOUND, MessageConstant.CHECKPOINT_NOT_FOUND),
    CHECKPOINT_DUPLICATE_ORDER(4102, HttpStatus.BAD_REQUEST, MessageConstant.CHECKPOINT_DUPLICATE_ORDER),

    // Schedule
    SCHEDULE_NOT_FOUND(4201, HttpStatus.NOT_FOUND, MessageConstant.SCHEDULE_NOT_FOUND),
    SCHEDULE_HAS_BOOKINGS(4202, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_HAS_BOOKINGS),
    SCHEDULE_RETURN_BEFORE_DEPARTURE(4203, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_RETURN_BEFORE_DEPARTURE),
    SCHEDULE_DEPARTURE_IN_PAST(4204, HttpStatus.BAD_REQUEST, MessageConstant.SCHEDULE_DEPARTURE_IN_PAST),

    // Blog
    BLOG_NOT_FOUND(5001, HttpStatus.NOT_FOUND, MessageConstant.BLOG_NOT_FOUND),
    
    // Vendor
    VENDOR_NOT_FOUND(6001, HttpStatus.NOT_FOUND, MessageConstant.VENDOR_NOT_FOUND),
    EQUIPMENT_NOT_FOUND(6002, HttpStatus.NOT_FOUND, MessageConstant.EQUIPMENT_NOT_FOUND);
    TAX_CODE_ALREADY_EXISTS(6002, HttpStatus.BAD_REQUEST, MessageConstant.TAX_CODE_ALREADY_EXISTS),
    APPLICATION_PENDING_EXISTS(6004, HttpStatus.BAD_REQUEST, MessageConstant.APPLICATION_PENDING_EXISTS),
    VENDOR_APPLICATION_NOT_FOUND(6005, HttpStatus.NOT_FOUND, MessageConstant.VENDOR_APPLICATION_NOT_FOUND),
    CONTACT_EMAIL_ALREADY_EXISTS(6006, HttpStatus.BAD_REQUEST, MessageConstant.CONTACT_EMAIL_ALREADY_EXISTS),
    CONTACT_PHONE_ALREADY_EXISTS(6007, HttpStatus.BAD_REQUEST, MessageConstant.CONTACT_PHONE_ALREADY_EXISTS),
    UNAUTHORIZED_APPLICATION_ACCESS(6008, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_APPLICATION_ACCESS),
    APPLICATION_ALREADY_PROCESSED(6009, HttpStatus.BAD_REQUEST, MessageConstant.APPLICATION_ALREADY_PROCESSED),
    CANNOT_UPDATE_APPLICATION(6100, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_UPDATE_APPLICATION),
    CANNOT_SUBMIT_APPLICATION(6101, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_SUBMIT_APPLICATION),
    CANNOT_RESUBMIT_APPLICATION(6102, HttpStatus.BAD_REQUEST, MessageConstant.CANNOT_RESUBMIT_APPLICATION),
    INVALID_REVIEW_STATUS(6103, HttpStatus.BAD_REQUEST, MessageConstant.INVALID_REVIEW_STATUS),
    REJECTION_REASON_REQUIRED(6104, HttpStatus.BAD_REQUEST, MessageConstant.REJECTION_REASON_REQUIRED),
    UNAUTHORIZED_VENDOR_ACCESS(6010, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_VENDOR_ACCESS),
    VENDOR_REVOKED_STATUS(6011, HttpStatus.BAD_REQUEST, MessageConstant.VENDOR_REVOKED_STATUS),
    STAFF_ALREADY_EXISTS(6201, HttpStatus.BAD_REQUEST, MessageConstant.STAFF_ALREADY_EXISTS),
    STAFF_BELONGS_TO_OTHER_VENDOR(6202, HttpStatus.BAD_REQUEST, MessageConstant.STAFF_BELONGS_TO_OTHER_VENDOR),
    VENDOR_STAFF_NOT_FOUND(6203, HttpStatus.NOT_FOUND, MessageConstant.VENDOR_STAFF_NOT_FOUND),
    UNAUTHORIZED_STAFF_ACCESS(6204, HttpStatus.FORBIDDEN, MessageConstant.UNAUTHORIZED_STAFF_ACCESS);


    private final int code;
    private final HttpStatus httpStatus;
    private final String message;

    ErrorCode(int code, HttpStatus httpStatus, String message) {
        this.code = code;
        this.httpStatus = httpStatus;
        this.message = message;
    }
}
