package com.sep.treksphere.enums.system;

public enum NotificationEventType {
    BOOKING_CREATED, BOOKING_PENDING_CONFIRMATION, BOOKING_CONFIRMED,
    BOOKING_REJECTED, BOOKING_CANCELLED, BOOKING_EXPIRED, PAYMENT_SUCCESS, NEW_MESSAGE,
    TOUR_APPROVED, TOUR_PENDING_APPROVAL, TOUR_HIDDEN_VIOLATION, GROUP_JOIN_REQUEST,
    SCHEDULE_UPDATED, TOUR_REJECTED, REFUND_PENDING, REFUND_MANUAL_REVIEW,
    REFUND_OVERDUE, REFUND_COMPLETED
}
