package com.sep.treksphere.enums.system;

public enum NotificationEventType {
    BOOKING_CONFIRMED, BOOKING_CANCELLED, PAYMENT_SUCCESS, NEW_MESSAGE,
    TOUR_APPROVED, TOUR_PENDING_APPROVAL, TOUR_HIDDEN_VIOLATION, GROUP_JOIN_REQUEST, TOUR_REJECTED
}